import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Helo?",
  description: "Generated by create next app",
};

const page = () => {
  return <div>Prislista</div>;
};

export default page;
